### ISSUE TITLE
Choropleth on categorical values

### ISSUE THREAD

**Issue by helgasoft** [helgasoft/echarty#14]
Do categorical values work for choropleth maps? asked [here](https://github.com/JohnCoene/echarts4r/issues/460) by @lgnbhl
ECharts seems to ignore non-numerical categories in piecewise choropleths. But numerical categories work.
```r
cns <- countrycode::codelist$country.name.en
cns <- data.frame(
	country = cns,
#	category = sample(LETTERS[1:4], length(cns), replace=TRUE, prob=c(0.1, 0.2, 0.65, 0.05))
	category = sample(1:4, length(cns), replace=TRUE, prob=c(0.1, 0.2, 0.65, 0.05))
)
# set colors for categories
colors <- c('#8b0069','#75c165', '#ce5c5c', '#fbc357')
pieces <- lapply(unique(cns$category), function(x) { 
	list(value= x, label= LETTERS[x], color= colors[x]) 
})

library(echarty)
cns |> ec.init(load= 'world', visualMap= list(type= 'piecewise', pieces=pieces) )
```
![image](https://user-images.githubusercontent.com/13038071/189220769-dc62b700-1007-4f3c-b3cd-96527939a641.png)
if you like this solution, please consider granting a Github star ⭐  to [echarty](https://github.com/helgasoft/echarty).

**Comment by lgnbhl** [comment]
Thank you for the explanation and for the solution using echarty :)

**Comment by helgasoft** [comment]
Felix, maybe this is what you want?
```r
library(dplyr)
cns <- countrycode::codelist$country.name.en
cns <- data.frame(
    country = cns,
    category = sample(LETTERS[1:4], length(cns), replace=TRUE, prob=c(0.1, 0.2, 0.65, 0.05))
) |> 
  mutate(numbas= match(category,LETTERS)) |>   # keep them in sync
  relocate(numbas, .after= country)	# default Y-axis is the second column
palet <- c('#8b0069','#75c165', '#ce5c5c', '#fbc357')
fmtr <-  htmlwidgets::JS("function (x) { return x.data[0]+'<br>cat: <b>'+x.data[2]; }")

library(echarty)
cns |> ec.init(load= 'world', 
    tooltip= list(show= TRUE),
    visualMap= list(type= 'piecewise', 
	    inRange= list(color= palet),
	    outOfRange= list(color= 'grey'),
	    categories= LETTERS[1:4], 
            dimension= 2)) |>   # JS count: 2 is position of 'category' column
ec.upd({ series[[1]]$tooltip <- list(formatter= fmtr) })  # update preset
```
![image](https://user-images.githubusercontent.com/13038071/189417923-1518cde2-a92a-4388-a579-80f7d78a8d92.png)

if you like this solution, please consider granting a Github star ⭐  to [echarty](https://github.com/helgasoft/echarty).

**Comment by lgnbhl** [comment]
Thanks you so much! Yes, it is exactly what I wanted.

However, I am not able to reproduce it with the R package "echarts4r": https://github.com/JohnCoene/echarts4r/issues/460#issuecomment-1242675482
