### ISSUE TITLE
Combinations of echarts4r and charty

### ISSUE THREAD

**Issue by rdatasculptor** [helgasoft/echarty#18]
Hi @helgasoft,

I have just a question/thought. For me the interface of `echarts4r` is a little bit easier for me to understand than `echarty`. On the other hand `echarty` seems much more capable of unleash all the features that echarts has. Do you think there is somehow a way to combine the two packages, e.g. by building and lay-outing a chart with a echarts4r and adding features, charts, morphs, etc. with the help of charty?

You have this nice function that translates a js echarts object into an (echarty-) R object. I was thinking of a similar translator function that tranlates an echarts4r-object into a echarty-object.

I know this will probably a much too complicated way to go, but I am curious about your opinion on this.

Thanks in advance!

**Comment by helgasoft** [comment]
Combine the two packages is, as you say, a "much too complicated way to go", got to choose one.
_echarts4r_ is user-friendly because it encapsulates a lot of settings internally. 
Advanced users however need more control, _echarty_ was born of this necessity.
The idea behind _echarty_'s API is "_why encapsulate when we can use the [ECharts API](https://echarts.apache.org/en/option.html) directly?_".
It is like C# vs C++, different ways of getting it done. A question of preference or necessity.

As a side note: both packages have functions to inspect their final _option_ sent to ECharts.js
```r
library(echarts4r)
cars |> e_charts(speed) |> e_scatter(dist) |> e_inspect(json=TRUE, pretty=TRUE)
library(echarty)
cars |> ec.init() |> ec.inspect()  # first 2 columns taken by default as x,y
```

**Comment by rdatasculptor** [comment]
Yes, I understand. And thanks for putting me in the direction of the inspect-functions! 

And last but not least, thank you for all the effort you put in `echarty`! I can clearly see its power and its additional value compared to `echarts4r`

**Comment by rdatasculptor** [comment]
I think made a first "integration" of `echarts4r` and `echarty`... kind of... :) 

```
library(echarts4r)
library(echarty)

df <- data.frame(
  year = c(
    rep(2016, 25),
    rep(2017, 25),
    rep(2018, 25),
    rep(2019, 25)
  ),
  x = rnorm(100),
  y = rnorm(100),
  grp = c(
    rep("A", 50),
    rep("B", 50)
  )
) 

txt <- df |> 
  group_by(year) |> 
  e_charts(x, timeline = TRUE) |> 
  e_scatter(y) |> 
  e_loess(y ~ x) |> 
  e_inspect(json=TRUE, pretty=TRUE)

ec.fromJson(txt)
```
And now I am wondering.. Could this potentially be a way for echarts4r users to bring crosstalk features to echarts4r... somehow... (@JohnCoene).

**Comment by helgasoft** [comment]
Aah, trailblazing, love it 🥇  , and going straight to *crosstalk* - ambitious!
However... crosstalk is communication between htmlwidgets and is not 'recorded' in the exported JSON.
Also, _echarty_ implements crosstalk thru ECharts [dataset](https://echarts.apache.org/en/option.html#dataset) which is not supported by _echarts4r_.
So I do not see a way of adding somehow crosstalk capabilities to _echarts4r_ via _echarty_.

But your idea opens other possibilities of graphical integration. 
Here is a playful one - adding [lotties](https://lottiefiles.com) to _echarts4r_ charts:
```r
# df <- ...
txt <- df |> 
#	group_by(year) |> 
	e_charts(x) |> #, timeline = TRUE) |>   # lotties can't be used in timeline (yet)
	e_scatter(y) |> 
	e_loess(y ~ x) |> 
	e_inspect(json=TRUE, pretty=TRUE)
p4 <- ec.fromJson(txt)

json <- 'https://raw.githubusercontent.com/airbnb/lottie-ios/edf0afcfaf7e0bd37f9311a3502b2981aa8a37f2/Tests/Samples/PinJump.json'
cont <- jsonlite::fromJSON(json, simplifyDataFrame=FALSE)
# set only graphic option in echarty
py <- ec.init(preset=FALSE,
	load='https://helgasoft.github.io/echarty/js/lottie-parser.js',
	graphic= list(elements= list(
		 list( type= "group", 
		 	# lottie params = info + optional (scale, loop, etc.)
		 	info= cont, scale= 250, # loop= FALSE,
		 	left= 'center', bottom= '20%'  #,rotation= -20
		 )
	)) )
# merge p4 & py options
py$x$opts <- append(py$x$opts, p4$x$opts)
py

```
![image](https://user-images.githubusercontent.com/13038071/194618528-fe9c4660-d18b-489a-945f-b1cd7ebf97a8.png)

**Comment by rdatasculptor** [comment]
Yesssssss! It opens an new world to explore (at least for me it does).

Thanks again @helgasoft!! This is very very inspiring. 
(And thank you for the technical explanation of crosstalk)
