### ISSUE TITLE
Separate symbols/custom shapes | Within timeline frames

### ISSUE THREAD

**Issue by MrMisc** [helgasoft/echarty#28]
As a continuation of my earlier question, I was wondering if it there is a way that echarty could let a user set a custom "symbol" for each group within a frame inside a timeline animation?

I have been able to categorize frames within timelines via colour and size thanks to echarty and helgasoft's help, but I was wondering if there was also this other possibility? The only solution I vaguely recall ever seeing was manually adding separate "traces" for each group but I don't think that would be reproducible for varying numbers of groups and esapecially different numbers of frames in timeline.

**Comment by helgasoft** [comment]
Hope this is the answer. There are two ways of setting group symbols:
* thru _tl.series$symbol_
* with _ec.upd()_

The second method has the advantage of showing symbols in the **legend** as well.
```
set.seed(222); N<- 22
df <- data.frame(x = runif(N,1,20),
                 y = runif(N,10,25),
                 z = rnorm(N,100,50),
    Time = runif(N,5,500),
    label = sample(c("interaction1", "interaction2"), N, replace= TRUE),
    zone = sample(c("zone0", "zone1"), N, replace = TRUE))
df <- df |> mutate(symbol= ifelse(label=="interaction1", 'triangle',
    'path://M 10,30 A 20,20 0,0,1 50,30 A 20,20 0,0,1 90,30 Q 90,60 50,90 Q 10,60 10,30 z')) |>
    relocate(zone, .after= .Last.value)   # zone column last for 3D default tooltip

library(echarty)          # latest Github version
df  |> group_by(zone) |> arrange(label) |> 
ec.init(load='3D', tooltip= list(show= T),
    tl.series= list(type= 'scatter3D', groupBy= 'label', 
                    symbol= ec.clmn('symbol')),
    visualMap= list(dimension=4, inRange= list( symbolSize = c(35,5)))
    ,options= list(title= NULL)  # disable preset title
)
# )  |>      # alternative symbol setting with chained ec.upd
# ec.upd({
#   options <- lapply(options, \(oo) {
#     oo$series <- lapply(oo$series, \(ss) {
#       ss$symbol <- if (ss$name=="interaction1") 'triangle' else 'diamond'
#       ss
#     })
#     oo
#   })
# })
```
![image](https://github.com/helgasoft/echarty/assets/13038071/d6858502-06b4-4223-ac59-273387607649)
if you like this solution, please consider granting a Github star ⭐
