### ISSUE TITLE
Understanding formatter

### ISSUE THREAD

**Issue by MrMisc** [helgasoft/echarty#33]
Apologies, I would like to ask for some help understanding how I can be leveraging formatter in the following 
[example.csv](https://github.com/helgasoft/echarty/files/13693595/example.csv)

```r
big<-read.csv("example.csv")
big %>% mutate(Percent = Total_Divorces/`Aggregate Marriages`*100) %>%  group_by(Seed) %>% arrange(Year) |> ec.init(
  tooltip= list(show= TRUE,trigger = 'axis', formatter= 
                  ec.clmn('Cohort <b>%@</b><br> Year <b>%@</b><br> Percentage  <b> %@% </b>',1,2,8)),
  tl.series= list(encode = list(x = 'Year',y = 'Percent',emphasis = list(focus ="adjacency")),type= 'line'),
  xAxis = list(max = 2023,min = 1980),
  legend = setting,
)
```

Currently, my version of this timeline plot does not manage to present any of the values that I was meaning to showcase - 'Seed','Year' and 'Percent'.

**Comment by helgasoft** [comment]
good question - _ec.clmn()_ for tooltip formatter will work only when _trigger='item'_, but not when  _trigger='axis'_. We should clarify this in the docs. 
Trigger 'axis' has multiple sets of values instead of a single set, and the simplest solution is to **not use a formatter**, just ```trigger=list(show=T)```.  If you still want to do formatting, it needs to be done in a Javascript function. 
One could peek at the available data using ```formatter= ec.clmn('json')``` on screen, or ```formatter= ec.clmn('log')``` in Chrome console.

**Comment by MrMisc** [comment]
Ahh I see! Thank you for the clarification!

May I also get help understanding how to call the columns if I do a groupby for the first column? I think trying to call the 'Seed','Year' and 'Percent' columns didn't work when I quoted columns 1,2,8 like I did in this example.

**Comment by helgasoft** [comment]
> I think trying to call the 'Seed','Year' and 'Percent' columns didn't work when I quoted columns 1,2,8 like I did in this example.

First, as I mentioned, trigger has to be type='item'. Then 'Percent' is column #⁠9, not #⁠8. 
The first column 'X' is just an ID, you probably do not want to group on it.
This formatter example works as it should:
```
big<-read.csv("https://github.com/helgasoft/echarty/files/13693595/example.csv")
big %>% filter(Year==2019) %>% 
  mutate(Percent = Total_Divorces/`Aggregate.Marriages`*100) %>% 
  arrange(Year) %>%  group_by(Seed) |> 
ec.init(
  tooltip= list( trigger= 'item', formatter= 
        ec.clmn('Cohort <b>%@</b><br> Year <b>%@</b><br> Percentage  <b> %@% </b>',1,2,9)),
  series.param= list(type= 'line', encode = list(x= 'Year',y= 'Percent')),
  ,xAxis = list(scale=T)
)
```
