### ISSUE TITLE
Is GL screenshot possible

### ISSUE THREAD

**Issue by Nithador** [helgasoft/echarty#35]
Is it possible to do a screenshot for the 3D GL plots programmatically?

I would like to create a series of pictures and programmatically save static PNG of those pictures.

**Comment by Nithador** [comment]
Thanks, this shows the button to download png and I need to click it. What I meant was whether there is a way to store a result without human interaction.

From some search I saw, that  [getDataURL](https://echarts.apache.org/en/api.html#echartsInstance.getDataURL) could be used to the instance and save the image. However, I am not sure whether it is possible in R or RStudio, taking an instance from the Viewer pane for example.

Here they describe how this could be achieved in echarts [](https://stackoverflow.com/questions/43946865/can-i-save-chart-as-image-without-toolbox-interaction-in-echarts)

**Comment by helgasoft** [comment]
yes, _[getDataURL](https://echarts.apache.org/en/api.html#echartsInstance.getDataURL)_ is the way to go.
Here is how to do it hands-off with R libraries _shiny_ and _png_. 
```
library(shiny); library(echarty)
runApp( list(
  ui= fluidPage( ecs.output("plot") ),
  server= function(input, output, session) {
    data <- data.frame(
      x = c(1, 0, 0.6, 0.4),
      y = c(1, 2, 0, 2),
      z = c(0, 0, 2, 2) )
    jcode <- "function() {
      png = this.getDataURL({pixelRatio: 2, backgroundColor: '#fff'});
      if (png.startsWith('data') && png.length>33)
        Shiny.setInputValue('png64', png)
    }"

    output$plot <- ecs.render({
      p <- ec.init(load= '3D',
                   series= list(list(type= 'surface', data= ec.data(data)))
      )
      # catch moment when image is ready
      p$x$on <- list(list(event= 'finished', handler= ec.clmn(jcode) ))
      p
    }) 

    observeEvent(input$png64, {
      tmp <- input$png64
      bin <- base64enc::base64decode(what= substr(tmp, 23, nchar(tmp)))
      png::writePNG(png::readPNG(bin), "plot.png")
    })
  }
))
```

**Comment by Nithador** [comment]
Perfect! This works and I can proceed from here. Thank You very much for a quick response and help.

**Comment by rdatasculptor** [comment]
Also there is a way to use webshot2 for this. You can take a look [here](https://github.com/JohnCoene/echarts4r/issues/528#issue-1743224350) for some inspiration.

**Comment by helgasoft** [comment]
Thanks @rdatasculptor - good alternative, it works.
```
#' from https://gist.github.com/dantonnoriega/0744e7537076128ac4a026b8b7f38f09
pp <- cars |> echarty::ec.init()
OUTPUT_HTML <- '~/TEST'
html <- file.path(OUTPUT_HTML, "tstPng.html")
htmlwidgets::saveWidget(pp, file= html, libdir= 'html_files') # save html widget
# make pngs
htmls <- list.files(OUTPUT_HTML, pattern = "html$", full.names = TRUE) # list of all html files
pngs <- lapply(htmls, function(j) { # search folder for html widgets, convert to png
  dir <- normalizePath(OUTPUT_HTML)
  out <- file.path(dir, gsub("html", "png", basename(j))) # copy name
  message(sprintf("Generating... %s", out))
  webshot2::webshot(j, file= out, delay=0) #, vwidth=1500, vheight=500, zoom=2)
})
```

**Comment by rdatasculptor** [comment]
Neat and quick response! Interesting script, Thanks.
