### ISSUE TITLE
e_theme

### ISSUE THREAD

**Issue by antoine4ucsd** [helgasoft/echarty#37]
thank you for this nice suite of tools!
is there an equivalent for this
e_theme_custom('{"color":["#5B82D8","#f2bc40","#b9257a","#448c8a"]}')

thank you!

**Comment by helgasoft** [comment]
Yes, there is an example in the _ec.theme_ help (?ec.theme). Here is one with your data.
```
cars |> ec.init(series.param=list(colorBy='data')) |> 
ec.theme('themeName', code='{"color":["#5B82D8","#f2bc40","#b9257a","#448c8a"]}')
```

**Comment by antoine4ucsd** [comment]
thank you so much!
