### ISSUE TITLE
Echarty and dendrogram

### ISSUE THREAD

**Issue by BigD7** [helgasoft/echarty#4]
Can you please advise how to plot the result of an R hierarchical clustering procedure in Echarts via echarty?

Such as,

hc <- hclust(dist(USArrests), "ave")
plot(hc)
dend1 <- as.dendrogram(hc)

Thanks!

**Comment by helgasoft** [comment]
Cluster dendrograms are [not yet supported](https://github.com/apache/echarts/issues/13274) in ECharts.
There is a native cluster processing through **ecStat** - see [example1](https://echarts.apache.org/examples/en/editor.html?c=scatter-clustering), [example2](https://echarts.apache.org/examples/en/editor.html?c=scatter-clustering-process) or [our example with R](https://rpubs.com/echarty/ecStat).
All those examples end up with a scatter chart, but the dendrogram is a hierarchical type.
There are several types of charts to represent hierarchical structures in ECharts - sunburst, tree, treemap, sankey, graph, see [our R examples](https://helgasoft.github.io/echarty/uc3.html).
The tree chart is closest to a dendrogram. Below is a sample implementation.
Interactivity - tree could be zoomed, moved, nodes collapsed.
```r
hc <- hclust(dist(USArrests), "ave")
# decode hc$merge with hc$labels
inew <- list()
i <- 0
tmp <- apply(hc$merge, 1, function(x) {  #browser()
	fst <- if (x[1]<0) hc$labels[-x[1]] else inew[[x[1]]]$p[1]
	snd <- if (x[2]<0) hc$labels[-x[2]] else inew[[x[2]]]$p[1]
	i <<- i+1
	inew <<- append(inew, list(list(p=rep(paste0('p',i),2), c=c(fst, snd))) )
})
tmp <- unlist(inew)
parents <- c(); children <- c()
for(i in 1:length(tmp)) { 
	if (startsWith(names(tmp[i]), 'p')) 
	     parents <<- c(parents, tmp[i])
	else children <<- c(children, tmp[i])
}
# add top element
children <- c(unname(children), unname(tail(parents,1)))
parents <- c(unname(parents), '')

df <- data.frame(parents=parents, children=children)
tmp <- data.tree::FromDataFrameNetwork(df)
json <- data.tree::ToListExplicit(tmp, unname=TRUE)

library(echarty)
p <- ec.init(preset=FALSE)
p$x$opts$title <- list(text= 'Dendrogram from tree')
p$x$opts$series <- list(list( 
	orient= 'TB', roam= TRUE, initialTreeDepth= -1,  # initially show all
	type='tree', data=json$children, symbolSize= 15,
	# exclude names like 'p99', leave only state names
	label= list(formatter=htmlwidgets::JS(
		"function(n) { out= n.name.length<=3 ? '' : n.name; return out; }"), 
		offset= c(-12,0)), 
	leaves= list(label= list(position= 'middle',	rotate= 90,	
		 verticalAlign= 'top', align= 'right' ))
))
p

```
![image](https://user-images.githubusercontent.com/13038071/152257512-5e08ea6a-add5-4cfc-82ab-e7fab251041f.png)

**Comment by BigD7** [comment]
Great, thanks very much!

**Comment by helgasoft** [comment]
Here is new shorter code with latest echarty v.1.4.4.9000
```r
# 1) prepare data
# hc <- hclust(dist(iris), "complete"); scale <- 5
hc <- hclust(dist(USArrests), "ave"); scale <- 0.33
subt <- paste(as.character(hc$call)[2:3], collapse=' ')

# 2) plot, for chart parameters see https://echarts.apache.org/en/option.html#series-tree
library(echarty)
p <- ec.init(preset=FALSE) |> ec.theme('dark-mushroom')
p$x$opts$title <- list(text= 'Dendrogram', subtext= subt)
p$x$opts$tooltip <- list(show= TRUE)
p$x$opts$series <- list(list( 
  type= 'tree', 
  data= ec.dendro(hc), 
  roam= TRUE, initialTreeDepth= -1,  # initially show all
  symbolSize= ec.clmn(-1, scale= scale), 
  # exclude added labels like 'p99', leaving only the originals
  label= list(formatter= htmlwidgets::JS(
  	"function(n) { out= /p\\d+/.test(n.name) ? '' : n.name; return out;}"),
    offset= c(-12,0)),
  orient= 'TB',
  leaves= list(label= list(position= 'middle',	rotate= 90,
  	verticalAlign= 'top', align= 'right' ))
  # layout= 'radial'   # comment out leaves,offset,orient
  ,tooltip= list(formatter= "h={c}")
))
p
```

**Comment by BigD7** [comment]
Hi,

I’m sorry it took me so long to get back to this, but I appreciate the reply you provided.

I tried running the code below in  the latest version of Echarty (1.4.5) but it doesn’t recognize ec.dendro.

Can you help?

Thanks,
Alan

**Comment by helgasoft** [comment]
Alan,
_ec.dendro_ was merged in _ec.data_ in v.1.4.5.
Instead of ```data= ec.dendro(hc)``` the code is now: 
```r
data = ec.data(hc, format='dendrogram')
```
Changes like that are described in [NEWS](https://github.com/helgasoft/echarty/blob/main/NEWS.md).  One can also find details through [repo search](https://github.com/helgasoft/echarty/search?q=dendrogram).

**Comment by BigD7** [comment]
Thanks for the tips!
