### ISSUE TITLE
ECharts + GL and mobile touch devices

### ISSUE THREAD

**Issue by helgasoft** [helgasoft/echarty#6]
Apparently ECharts is focusing more on desktop implementations, less on mobile.
For instance more than half of [3D globe examples](https://echarts.apache.org/examples/en/index.html#chart-type-globe) do **not** show up on mobile.

[Another issue](https://github.com/apache/echarts/issues/9906) is that a simple touch(click) does not work on mobile devices for 3D Globe.
Luckily, thanks to @7upcat and @uozanyildiz, there is a workaround to enable this behaviour.
However the fix involves commenting out a line in the core library [echarts.js](https://github.com/apache/echarts/blob/master/dist/echarts.js#4591) - not very practical.
In latest v.5.3.2 this line is #4591 ```scope.touching = true;```.
[Here is a mobile JS demo](https://helgasoft.github.io/echarty/test/globe.touch.html) of 3D Globe working with a fixed _echarts.js_. 

Attn @CyprienCambus - in R/echarty same improvement is achieved by replacing library file _C:/Users/username/Documents/R/win-library/4.1/echarty/js/echarts.min.js_ with the fixed one.

Hopefully @pissang & team will address this bug soon. Until then we are planning to incorporate the fix in future releases of _echarty_.

**Comment by CyprienCambus** [comment]
Thanks a lot for your help ! I'll have a look. Anyway I did not know echarty and it looks awesome. Very good job
