### ISSUE TITLE
Grouping input data distorts parallel plot

### ISSUE THREAD

**Issue by yogat3ch** [helgasoft/echarty#7]
Hi @helgasoft,
Hope this finds you well!
I'm attempting to add a legend & colors to a parallel plot and I'm finding that grouping the input data (which appears necessary to enable the legend & colors) works to add the legend & colors but the lines are completely distorted. 
Any ideas on what's happening here?
```
mtcars |> head(8) |> tibble::rownames_to_column("ID") |> tibble::remove_rownames() |> dplyr::group_by(ID) |>  echarty::ec.init(ctype = "parallel")
```
![image](https://user-images.githubusercontent.com/32208821/165970643-b6285c08-b62b-48b4-b37c-125f295782cc.png)

**Comment by helgasoft** [comment]
echarty assumes the first 2-3 data columns to be default XY(Z) values. Sorry, this is <ins>not</ins> well emphasized in the documentation.
Parallel chart is not a conventional XY chart, but still *"does not like"* the grouping column to be first column. This is the cause of the distortion. By moving the grouping column last, chart displays correctly.

```r
mtcars |> head(8) |> tibble::rownames_to_column("ID") |>    
        # tibble::remove_rownames() |>         # does not affect layout
	relocate(ID, .after= last_col()) |>    # move grouping column last
	dplyr::group_by(ID) |>  echarty::ec.init(ctype= "parallel")
```

**Comment by yogat3ch** [comment]
Hi @helgasoft ,
Thank you for the tip regarding the positioning of the grouping column! That indeed resolved the distortion in the plot!

**Comment by yogat3ch** [comment]
I was also wondering ... [our small team is looking for a Shiny developer](https://community.rstudio.com/t/virga-labs-virgalabs-io-r-shiny-front-end-developer/134997), are you considering full-time work?
