### ISSUE TITLE
Grouping by multiple columns, groups inside timeline

### ISSUE THREAD

**Issue by helgasoft** [helgasoft/echarty#8]
Interesting [issue](https://github.com/JohnCoene/echarts4r/issues/435) raised by @XiangyunHuang on how to define groups inside ECharts timeline.
By default _echarty_ v.1.4.5 supports data grouping by **one** column only.  For timeline this column will define the timeline axis and labels.  Here is how it looks:
```r
set.seed(2022)
# echarty requires group column()s last or use dplyr::relocate before group_by
dat <- data.frame(
	x3 = runif(16),
	x4 = runif(16),
	x5 = abs(runif(16)),
	x1 = rep(2020:2023, each = 4), 
	x2 = rep(c("A", "A", "B", "B"), 4)
)
library(echarty); library(dplyr)
# preset timeline with one-column grouping
p <- dat |> group_by(x1) |> ec.init(
	tl.series= list(encode= list(x= 'x3', y= 'x5'), 
		        symbolSize= ec.clmn(2, scale=30))    # x4 is size, position 2
)
p
# p |> ec.inspect()   # look at presets
```
![image](https://user-images.githubusercontent.com/13038071/172714386-3909baed-f2b4-4ea1-8786-a94017bc071d.png)

But what if, according to @XiangyunHuang, we want to see groups A and B from column x2 inside each timeline year (x1) ?
<details>
  <summary>Click to see previous answer</summary> 
Astute data modification can accomplish this effect. The following solution is based on ECharts [data transformations](https://echarts.apache.org/en/tutorial.html#Data%20Transform).
Lets use the [dataset](https://echarts.apache.org/en/option.html#dataset) and [series](https://echarts.apache.org/en/option.html#series-scatter.type) preset by _echarty_. Then define additional dataset transformations and series and link them together to create **groups inside timeline options**.
Note: first dataset is always type 'source', others are type 'filter'.

```r
set.seed(2022)
dat <- data.frame(
	x3 = runif(16),
	x4 = runif(16),
	x5 = abs(runif(16)),
	x1 = rep(2020:2023, each = 4),
	x2 = rep(c("A", "A", "B", "B"), 4)
) 
# preset timeline by one-column grouping
library(echarty); library(dplyr)
p <- dat |> group_by(x1) |> ec.init(
	tl.series= list(encode= list(x= 'x3', y= 'x5'), 
		        symbolSize= ec.clmn(2, scale=30)) 
)

# define additional filter transformations and option series based on preset ones
dsf <- list()  # new filters
opts <- list()  # new options
filterIdx <- 0
for (i in 1:length(unique(dat$x1))) {
	snames <- c()
	for (x2 in unique(dat$x2)) {
		dst <- p$x$opts$dataset[[i+1]]  # skip source-dataset (1st)
		dst$transform$config <- list(and= list(
			dst$transform$config,
			list(dimension= 'x2', `=`= x2)
		))
		dsf <- append(dsf, list(dst))
		snames <- c(snames, x2)
	}
	opt <- p$x$opts$options[[i]]
	sss <- lapply(snames, function(s) {
		filterIdx <<- filterIdx + 1
		tmp <- opt$series[[1]]
		tmp$name <- s
		tmp$datasetIndex <- filterIdx
		tmp
	})
	opts <- append(opts, list(list(title= opt$title, series= sss)))
}
p$x$opts$dataset <- append(p$x$opts$dataset[1], dsf)   # keep source-dataset [1]
p$x$opts$options <- opts
p$x$opts$legend <- list(show=TRUE)
p 
```
</details>

**EDIT**:  this was too good to pass up - solution is now included in _echarty_ with new _tl.series_ attribute _groupBy_.
Below is code and result.  Thank you for the idea, @XiangyunHuang!

```r
if (!requireNamespace('remotes')) install.packages('remotes')
remotes::install_github('helgasoft/echarty')  # install v.1.4.5.9002 from Github

set.seed(2022)
dat <- data.frame(
  x3 = runif(16),
  x4 = runif(16),
  x5 = abs(runif(16)),
  x1 = rep(2020:2023, each = 4),
  x2 = rep(c("A", "A", "B", "B"), 4)
) 

library(echarty); library(dplyr)
p <- dat |> group_by(x1) |> ec.init(
  tl.series= list(encode= list(x= 'x3', y= 'x5'), 
                  symbolSize= ec.clmn(2, scale=30), 
                  groupBy= 'x2') 
)
p
```
![image](https://user-images.githubusercontent.com/13038071/172715668-2e27eaf6-65e2-4289-b5ac-5fd04634ce84.png)

If you like this solution, please consider granting a Github star ⭐  to [echarty](..).

**Comment by XiangyunHuang** [comment]
@helgasoft  Thanks! I like it, a Github star ⭐ was given to [echarty](https://github.com/helgasoft/echarty/).

<img width="560" alt="截屏2022-06-09 12 06 17" src="https://user-images.githubusercontent.com/12031874/172761993-6a0849ce-a3fc-402c-8dac-29244e94fe35.png">
